AWSTemplateFormatVersion: "2010-09-09"
Description: "This is the dns stack template. Resource defined on this template:
Route 53 Hosted Zone. This stack will not be created as a nested stack to avoid its deletion.
SSL Certificates requested direclty from console to avoid stack to be stuck in CREATE_IN_PROGRESS" 

Parameters:
  EnvironmentName:
    Type: String
    Default: "prod"
    Description: "Sets the environment."
  ProjectName:
    Type: String
    Description: "Projcet Name."
    Default: "universal"
  HostedZoneName: 
    Type: String

Resources:
  PublicDnsHostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: "DO NOT DELETE IT, hosted zone"
      Name: !Sub "${HostedZoneName}"
      HostedZoneTags:
        - 
          Key: auto-delete
          Value: never
        -
          Key: environment
          Value: !Ref EnvironmentName
        - 
          Key: project
          Value: !Ref ProjectName

Outputs:
  PublicDnsHostedZone:
    Description: Hosted Zone
    Value: !Ref PublicDnsHostedZone
    Export: 
      Name: PUBLIC-DNS-HOSTED-ZONE
  HostedZoneName:
    Description: base dns for other stacks
    Value: !Ref HostedZoneName
    Export: 
      Name: HOSTED-ZONE-NAME