---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This is the parent stack template for my-ha-architecture

Parameters:
  TemplatesBucket:
    Type: String
    Description: "This is the URL for the S3 bucket where the my-ha-architecture templates are stored."
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues: ["prod", "dev"]
    Description: "Sets the environment."
    ConstraintDescription: "must specify prod or dev."
  ProjectName:
    Type: String
    Description: "Projcet Name."
    ConstraintDescription: "must specified."

Resources:
  NetworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        - 
          Key: project
          Value: !Ref ProjectName
        -
          Key: environment
          Value: !Ref EnvironmentName
      Parameters:
        Environment: !Ref EnvironmentName
      TemplateURL: !Join [ /, [ "https://s3.amazonaws.com", !Ref TemplatesBucket, "network.yml" ] ]
  SecurityStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        - 
          Key: project
          Value: !Ref ProjectName
        -
          Key: environment
          Value: !Ref EnvironmentName
      Parameters:
        Environment: !Ref EnvironmentName
      TemplateURL: !Join [ /, [ "https://s3.amazonaws.com", !Ref TemplatesBucket, "security.yml" ] ]
  ComputeStack:
    DependsOn: NetworkStack
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        - 
          Key: project
          Value: !Ref ProjectName
        -
          Key: environment
          Value: !Ref EnvironmentName
      Parameters:
        Environment: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcHA
        PublicSubnet101Id: !GetAtt NetworkStack.Outputs.PublicSubnet101
        PublicSubnet102Id: !GetAtt NetworkStack.Outputs.PublicSubnet102
        PublicSubnet103Id: !GetAtt NetworkStack.Outputs.PublicSubnet103
        EcsTaskExecutionRole: !GetAtt SecurityStack.Outputs.EcsTaskExecutionRole
        EcsServiceRole: !GetAtt SecurityStack.Outputs.EcsServiceRole
        EcsTaskRole: !GetAtt SecurityStack.Outputs.EcsTaskRole
      TemplateURL: !Join [ /, [ "https://s3.amazonaws.com", !Ref TemplatesBucket, "compute.yml" ] ]
  
Outputs:
  NetworkStack:
    Description: ARN of network nested Stack
    Value: !Ref NetworkStack
    Export:
      Name: NETWORK-STACK-ID
  ComputeStack:
    Description: ARN of compute nested Stack
    Value: !Ref ComputeStack
    Export:
      Name: COMPUTE-STACK-ID
  SecurityStack:
    Description: ARN of security nested Stack
    Value: !Ref SecurityStack
    Export:
      Name: SECURITY-STACK-ID
