---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This is the security stack template for my-ha-architecture. Resource defined on this template: IamRoles, WAFs" 

Parameters:
  Environment:
    Type: String
    AllowedValues: ["prod", "dev"]
    Description: "Sets the environment."
    ConstraintDescription: "must specify prod or dev."
  DomainNameForCertificate:
    Type: String
    Default: "*.cirrus.com"
    Description: "FQDN in certificate request."

Resources:
  
Outputs:
